# Generated by Django 6.0.4 on 2026-04-12 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=60, unique=True)),
                ('transcription', models.TextField(blank=True)),
                ('transcription_confidence', models.FloatField(default=0)),
                ('language', models.CharField(default='en-US', max_length=10)),
                ('primary_mood', models.CharField(blank=True, max_length=30)),
                ('secondary_mood', models.CharField(blank=True, max_length=30)),
                ('mood_confidence', models.FloatField(default=0)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('intent_type', models.CharField(blank=True, max_length=50)),
                ('context', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
