# Generated by Django 6.0.4 on 2026-04-12 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_id', models.CharField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=50)),
                ('emoji', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Mood Categories',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rating', models.FloatField(default=4.0)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.URLField(blank=True)),
                ('category', models.CharField(max_length=50)),
                ('cuisine', models.CharField(max_length=50)),
                ('rating', models.FloatField(default=4.0)),
                ('reviews_count', models.IntegerField(default=0)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('preparation_time', models.IntegerField(default=20)),
                ('calories', models.IntegerField(default=400)),
                ('protein', models.CharField(default='15g', max_length=10)),
                ('carbs', models.CharField(default='40g', max_length=10)),
                ('fat', models.CharField(default='10g', max_length=10)),
                ('ingredients', models.JSONField(default=list)),
                ('customizations', models.JSONField(default=list)),
                ('mood_tags', models.JSONField(default=list)),
                ('order_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.restaurant')),
            ],
        ),
    ]
