import os
import json
import base64
import asyncio
import traceback
from google import genai

async def handle_voice_websocket(scope, receive, send):
    """
    ASGI WebSocket handler for live voice chat with Google Gemini.
    Accepts WebSocket connections, streams raw audio/text from the client,
    and returns voice audio/text generated by Gemini in real-time.
    """
    # 1. Accept the WebSocket connection
    await send({'type': 'websocket.accept'})
    
    # 2. Parse query parameters for user_id and session_id
    query_string = scope.get('query_string', b'').decode('utf-8')
    params = {}
    if query_string:
        for qc in query_string.split('&'):
            if '=' in qc:
                k, v = qc.split('=', 1)
                params[k] = v
                
    user_id = int(params.get('user_id', 1))
    session_id = params.get('session_id', 'default')
    
    print(f"[WebSocket] Connected: User {user_id}, Session {session_id}")
    
    # 3. Retrieve Google Gemini API Key and load env if not loaded
    api_key = os.environ.get('GOOGLE_GEMINI_API_KEY', '').strip()
    if not api_key:
        import dotenv
        # Try loading from the root of the project
        root_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
        dotenv.load_dotenv(os.path.join(root_dir, '.env'))
        api_key = os.environ.get('GOOGLE_GEMINI_API_KEY', '').strip()
        
    if not api_key:
        print("[WebSocket] Error: GOOGLE_GEMINI_API_KEY is not set.")
        await send({
            'type': 'websocket.send',
            'text': json.dumps({'error': 'GOOGLE_GEMINI_API_KEY is not set in environment or .env file.'})
        })
        await send({'type': 'websocket.close'})
        return
        
    client = genai.Client(api_key=api_key)
    
    instruction = (
        "You are the MoodBowl Voice Controller. Be an empathetic culinary assistant. "
        "Help the user find food based on their mood and cravings. "
        "Respond in a natural voice, and also provide structured text recommendations when asked."
    )
    
    config = {
        'system_instruction': instruction,
        'generation_config': {
            'response_modalities': ['AUDIO']
        }
    }
    
    try:
        # Connect to Gemini Live API
        # We use the official gemini-2.0-flash model for bidiGenerateContent
        async with client.aio.live.connect(model='gemini-2.0-flash', config=config) as session:
            print("[WebSocket] Connected to Gemini Live Session!")
            
            # Send initial greeting prompt to kick off the conversation
            await session.send(input="Please welcome the user to MoodBowl and ask how they are feeling today.", end_of_turn=True)
            
            # Task A: receive from browser -> send to Gemini
            async def browser_to_gemini():
                try:
                    while True:
                        event = await receive()
                        if event['type'] == 'websocket.disconnect':
                            print("[WebSocket] Client disconnected")
                            break
                        elif event['type'] == 'websocket.receive':
                            if 'text' in event and event['text']:
                                try:
                                    data = json.loads(event['text'])
                                    client_content = data.get('client_content', '')
                                    if client_content:
                                        print(f"[WebSocket] User text: {client_content}")
                                        await session.send(input=client_content, end_of_turn=True)
                                except json.JSONDecodeError:
                                    pass
                            elif 'bytes' in event and event['bytes']:
                                # Raw PCM audio bytes (16kHz PCM) from mic
                                await session.send(input={
                                    "data": event['bytes'],
                                    "mime_type": "audio/pcm;rate=16000"
                                })
                except asyncio.CancelledError:
                    pass
                except Exception as e:
                    print(f"[WebSocket] Error in browser_to_gemini stream: {e}")
                    
            # Task B: receive from Gemini -> send to browser
            async def gemini_to_browser():
                try:
                    async for response in session.receive():
                        if response.server_content and response.server_content.model_turn:
                            for part in response.server_content.model_turn.parts:
                                if part.text:
                                    payload = {"server_content": {"text": part.text}}
                                    await send({
                                        'type': 'websocket.send',
                                        'text': json.dumps(payload)
                                    })
                                elif part.inline_data:
                                    encoded_audio = base64.b64encode(part.inline_data.data).decode('utf-8')
                                    payload = {"server_content": {"inline_data": encoded_audio}}
                                    await send({
                                        'type': 'websocket.send',
                                        'text': json.dumps(payload)
                                    })
                except asyncio.CancelledError:
                    pass
                except Exception as e:
                    print(f"[WebSocket] Error in gemini_to_browser stream: {e}")
                    await send({
                        'type': 'websocket.send',
                        'text': json.dumps({'error': f'Gemini stream error: {str(e)}'})
                    })
            
            # Gather tasks
            done, pending = await asyncio.wait(
                [
                    asyncio.create_task(browser_to_gemini()),
                    asyncio.create_task(gemini_to_browser())
                ],
                return_when=asyncio.FIRST_COMPLETED
            )
            for task in pending:
                task.cancel()
                
    except Exception as e:
        print(f"[WebSocket] Gemini Connection Failed: {e}. Entering Mock interactive mode.")
        
        # Send initial mock greeting
        await send({
            'type': 'websocket.send',
            'text': json.dumps({
                "server_content": {
                    "text": "Welcome to MoodBowl! I am your AI waiter. I am currently running in local Demo Mode since a valid Gemini API Key is missing. Tell me, how are you feeling today?",
                    "is_mock": True
                }
            })
        })
        
        try:
            while True:
                event = await receive()
                if event['type'] == 'websocket.disconnect':
                    print("[WebSocket] Client disconnected (Mock Mode)")
                    break
                elif event['type'] == 'websocket.receive':
                    if 'text' in event and event['text']:
                        try:
                            data = json.loads(event['text'])
                            user_text = data.get('client_content', '').strip().lower()
                            if user_text:
                                print(f"[WebSocket] Mock Mode input: {user_text}")
                                reply = ""
                                if any(w in user_text for w in ["happy", "good", "great", "glad"]):
                                    reply = "That's wonderful to hear! Since you are in a happy mood, I recommend treating yourself to a Margherita Pizza or Mango Lassi. Would you like to order them?"
                                elif any(w in user_text for w in ["sad", "depressed", "down", "comfort"]):
                                    reply = "I'm sorry you are feeling down. How about some comfort food to warm you up? I highly recommend our Mac & Cheese Bowl or some hot Dal Makhani. Would you like to add one to your cart?"
                                elif any(w in user_text for w in ["stressed", "anxious", "worry", "tense"]):
                                    reply = "Stressed days are tough. Let's get you something calming and light, like a fresh Greek Salad or a warm Chamomile Honey Tea. Would that help you unwind?"
                                elif any(w in user_text for w in ["tired", "exhausted", "sleepy", "low energy"]):
                                    reply = "You sound exhausted! You need some rich energy fuel. Our Chicken Biryani or a warm Butter Chicken with naan is perfect to recharge you. Want to add that to your meal?"
                                elif any(w in user_text for w in ["healthy", "veg", "diet"]):
                                    reply = "Clean eating it is! Our Quinoa Buddha Bowl and Green Smoothie Bowl are packed with vitamins and taste amazing. Should I add them to your cart?"
                                elif any(w in user_text for w in ["add", "yes", "please", "sure", "order", "want"]):
                                    reply = "Perfect! I've added your recommended items to your cart. You can review your cart at the bottom tab whenever you're ready!"
                                else:
                                    reply = "I understand. I can recommend some tasty dishes matching your mood. Tell me, are you craving something spicy, sweet, or comforting?"
                                    
                                await asyncio.sleep(0.5)
                                await send({
                                    'type': 'websocket.send',
                                    'text': json.dumps({
                                        "server_content": {
                                            "text": reply,
                                            "is_mock": True
                                        }
                                    })
                                })
                        except json.JSONDecodeError:
                            pass
        except Exception as mock_err:
            print(f"[WebSocket] Mock session error: {mock_err}")
    finally:
        try:
            await send({'type': 'websocket.close'})
        except:
            pass
